apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: mapper
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:
            - name: MAPPER_SECRET_NAME
              value: "{{ .Values.secret.name }}"
            - name: MAPPER_NAMESPACE
              value: "{{ .Values.namespace }}"
            - name: MAPPER_PREFERRED_FIELD
              value: "{{ .Values.secret.preferred_field }}"
            - name: MAPPER_CONFIGMAP_NAME
              value: "{{ .Values.secret.config_map }}"
            - name: MAPPER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.secret.api_key }}"
                  key: token

          ports:
            - containerPort: {{ .Values.service.port }}

          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 2
            successThreshold: 1
