name: apisix-auth-mapper
namespace: apisix
replicaCount: 1

image:
  repository: apisix-auth-mapper
  tag: "v1.2.3-testrediness"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

secret:
  name: auth-mapper-secrets
  preferred_field: username
  config_map: auth-map

serviceAccount:
  name: mapper-sa
  namespace: apisix
  roleName: mapper-role
  roleBindingName: mapper-rolebinding
