name: apisix-auth-mapper
replicaCount: 1

image:
  repository: apisix-auth-mapper
  tag: "v2.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

secret:
  name: auth-mapper-secrets
  api_key: mapper-auth

mapper:
  preferred_field: preferred_username
  issuer: https://keycloak.preprod.integra.bankspb.ru/realms/integra

session:
  startURL: "https://10.81.170.133:8080/platform2mca-proxy/rest/auth/v1/session/basic"
  endURL: "https://10.81.170.133:8080/platform2mca-proxy/rest/auth/v1/session/"

readinessProbe:
  path: /healthz
  initialDelaySeconds: 2
  periodSeconds: 5
  timeoutSeconds: 1
  failureThreshold: 2
  successThreshold: 1
