name: apisix-auth-mapper
replicaCount: 1

image:
  repository: integration-platform.docker.bankspb.ru/apisix-auth-mapper
  tag: "v1.2.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

secret:
  name: auth-mapper-secrets

mapper:
  preferred_field: preferred_username

readinessProbe:
  path: /healthz
  initialDelaySeconds: 2
  periodSeconds: 5
  timeoutSeconds: 1
  failureThreshold: 2
  successThreshold: 1
