name: apisix-auth-mapper
replicaCount: 1

image:
  repository: apisix-auth-mapper
  tag: "v1.3.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

secret:
  name: auth-mapper-secrets
  api_key: mapper-auth

mapper:
  preferred_field: preferred_username
  issuer: https://keycloak.preprod.integra.bankspb.ru/realms/integra

readinessProbe:
  path: /healthz
  initialDelaySeconds: 2
  periodSeconds: 5
  timeoutSeconds: 1
  failureThreshold: 2
  successThreshold: 1
